server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 100MB
      # 파일 저장 경로  
      #location: D:\upload
    #ssl:
        
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-3-210-29-54.compute-1.amazonaws.com:5432/dago7l0bh15m9h
    username: mzisdquvibcqwi
    password: f863dc0af417316ca505786bdb97e8d0c5b2aa822a05ee3ccd9a59f6a8d18d0c
    
  jpa:
    database: POSTGRESQL
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: sophist.common.model.NamingStrategy
     
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
    
  jackson:
    serialization:
      fail-on-empty-beans: false
      
  logging: 
    config: classpath:log4j2-spring.xml
  external:
    file:
      ext:jpg|png|hwp
 
      
